# Generated by Django 5.2 on 2025-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_experience_years_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Marque esta opção se este usuário for um Personal Trainer.'),
        ),
    ]
