# Generated by Django 5.2 on 2025-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Liste aqui certificações, cursos ou especializações profissionais.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, help_text='Faculdade que este Personal frequentou (se aplicável).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_email',
            field=models.BooleanField(default=False, help_text='Se marcado, ocultará seu e-mail para outros usuários (apenas você verá seu e-mail).'),
        ),
    ]
