# Generated by Django 5.2 on 2025-05-23 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_certifications_profile_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Usuários que este Personal escolheu como alunos', related_name='personals', to=settings.AUTH_USER_MODEL),
        ),
    ]
