# Generated by Django 5.2 on 2025-04-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='descricao',
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('series', models.PositiveIntegerField()),
                ('repeticoes', models.PositiveIntegerField()),
                ('descanso', models.PositiveIntegerField()),
                ('carga_maxima', models.FloatField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.grupomuscular')),
            ],
        ),
    ]
