# Generated by Django 5.2 on 2025-04-19 14:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0003_treino_carga_total_treino_duracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao', models.DurationField(default=datetime.timedelta)),
                ('carga_total', models.FloatField(default=0.0)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.PositiveIntegerField()),
                ('carga_utilizada', models.FloatField()),
                ('duracao', models.DurationField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('execucao_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.execucaotreino')),
            ],
        ),
    ]
