# Generated by Django 5.2 on 2025-04-19 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_execucaotreino_execucaoexercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaotreino',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
