# Generated by Django 5.2 on 2025-04-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0005_alter_execucaotreino_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='treinos.treino'),
        ),
    ]
