# Generated by Django 5.2 on 2025-04-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0006_alter_execucaotreino_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino'),
        ),
    ]
