# Generated by Django 5.2 on 2025-05-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0008_compartilhamentotreino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartilhamentotreino',
            old_name='data_compartilhamento',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='compartilhamentotreino',
            name='aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compartilhamentotreino',
            name='de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_feitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compartilhamentotreino',
            name='para_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
